name: Schedule update

env:
  SURL_PRE: https://www.insidermonkey.com/insider-trading/company
  SURL_SUR: hedge-funds/
  IURL_PRE: https://www.insidermonkey.com/hedge-fund
  IURL_SUR: holdings/

  CASCADIA_V: 1.2.5
  CASCADIA_F: cascadia_${CASCADIA_V}_linux_amd64
 
  TZ: 'America/Toronto'


on:
  push:
  schedule:
    # * is a special character in YAML so you have to quote this string
    #- cron:  '5 18 * * */2'
    # At 18:05 *EST* (17:05 *EDT*) on every 2nd day-of-week. In UTC it is:
    - cron:  '5 13 * * */2'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  Update-file:
    # Link to the environment SG1 that provides secrets
    environment: HF
    runs-on: ubuntu-latest
    steps:
      # Checks-out repository under $GITHUB_WORKSPACE, so as to access it
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set env
        # makes it available to all subsequent actions in the current job
        # the currently running action cannot access the updated variable
        run: |
          echo "Started at $(date -Iseconds)"
          echo "$HOME/bin" >> $GITHUB_PATH
          echo "CASCADIA_F=cascadia_${CASCADIA_V}_linux_amd64" >> $GITHUB_ENV
          echo "today=$(date -I)" >> $GITHUB_ENV

      - name: Cache Binary
        uses: actions/cache@v2
        id: cache
        with:
          path: |
            ~/downloaded
            ~/bin
          key: bin_2021-07-17

      - name: Download Binary
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          mkdir -p ~/bin
          mkdir -p ~/downloaded
          cd ~/downloaded
          rm -f *
          # cascadia
          wget https://github.com/suntong/cascadia/releases/download/v${CASCADIA_V}/${CASCADIA_F}.tar.gz
          tar -tvzf ${CASCADIA_F}.tar.gz
          tar -xvzf ${CASCADIA_F}.tar.gz -C ~/bin
          ln -vs ${CASCADIA_F}/cascadia ~/bin
          # xsel
          wget https://github.com/suntong/xsel/releases/download/v0.9.7/xsel_0.9.7_linux_amd64.tar.gz
          tar -xvzf xsel_*.tar.gz -C ~/bin
          ln -vs xsel_0.9.7_linux_amd64/xsel ~/bin
          # 
          ls -l ~/bin ~/bin/${CASCADIA_F}
          ~/bin/${CASCADIA_F}/cascadia
          echo $PATH
          cascadia
          xsel -h

          cd ~/downloaded
          apt-get download tidy
          debFile=`ls tidy_*_amd64.deb`
          ar p $debFile data.tar.xz | tar xJv --strip-components=2 -f - -C ~/
          ls -l ~/bin
          tidy -version


      - name: Update
        run: |
          echo ls -l ~/bin
          ls -l ~/bin
          echo login with ${{secrets.UMAIL}}:${{secrets.UPASS}}
          curl 'https://www.insidermonkey.com/services/login.php'  --data-raw 'umail=${{secrets.UMAIL}}&upass=${{secrets.UPASS}}&rm=on&rurl=' -c ~/downloaded/cookies
          echo cookies
          cat ~/downloaded/cookies

          csvFile=HFS.csv
          while IFS="," read tick url
          do
            [ `expr "$tick" : '#'` -eq "1" ] && {
              echo "skipping: $tick"
              continue
            }
            echo "downloading $tick: $url"
            curl -b ~/downloaded/cookies $SURL_PRE/$url/$SURL_SUR | cascadia -o -i -c '#fund-holdings > div.subsection.holdings-container' --wrap-html --style '<link rel="stylesheet" href="insidermonkey.css">' | tidy --quiet yes --show-errors 0 --doctype omit --clean yes --tidy-mark no | sed '/<option value=/d' > S-$tick.html
          done < "$csvFile"
          csvFile=HFI.csv
          while IFS="," read instu
          do
            [ `expr "$instu" : '#'` -eq "1" ] && {
              echo "skipping: $instu"
              continue
            }
            instn=`echo $instu | sed -E 's|/.*$||; s/\+/_/g; s/%[[:xdigit:]]{2}//g'`
            echo "downloading $instn"
            curl -b ~/downloaded/cookies $IURL_PRE/$instu/$IURL_SUR | cascadia -o -i -c '#fund-holdings > div.subsection.holdings-container' --wrap-html --style '<link rel="stylesheet" href="insidermonkey.css">' | tidy --quiet yes --show-errors 0 --doctype omit --clean yes --tidy-mark no -asxhtml | sed '/<option value=/d; 1s/^.*$/<html>/' > I_$instn.html
          done < "$csvFile"

          echo xsel
          set -x
          xsel -x '//tr[./td[text()="NEW"]]' -m -n `cat HFI.csv | sed -E 's|/.*$||; s/\+/_/g; s/%[[:xdigit:]]{2}//g; s/^.*$/I_&.html/'` | tidy --quiet yes --show-errors 0 --doctype omit --clean yes --tidy-mark no > I_NEW.html || true
          printf "No. | Security | Ticker | Shares | Value (x\$1000) | Activity | %% Port\n|--- | --- | --- | ---:| ---:|:---:| ---:|\n " | tee I_NEW_sS.md I_NEW_sV.md I_NEW_sP.md
          cat I_NEW.html | grep -i -e '</\?TABLE\|</\?TD\|</\?TR\|</\?TH' | sed 's/^[\ \t]*//g' | tr -d '\n' | sed 's/<\/TR[^>]*>/\n/Ig'  | sed 's/<\/\?\(TABLE\|TR\)[^>]*>//Ig' | sed 's/^<T[DH][^>]*>\|<\/\?T[DH][^>]*>$//Ig' | sed 's/<\/T[DH][^>]*><T[DH][^>]*>/|/Ig; s/|\$/|/; s/<a href=//' | tee /tmp/t.md
          cat /tmp/t.md | LC_ALL=en_US.utf8 sort -t'|' -k4 -r -h | tee -a I_NEW_sS.md
          cat /tmp/t.md | LC_ALL=en_US.utf8 sort -t'|' -k5 -r -h | tee -a I_NEW_sV.md
          cat /tmp/t.md | sort -t'|' -k7 -r -g | tee -a I_NEW_sP.md

          ls -l

      - name: Commit changes
        uses: EndBug/add-and-commit@v7
        with:
          message: "- [#] updated on ${{env.today}}"
